#
# ApproxMC
#
# Copyright (c) 2009-2017, Mate Soos. All rights reserved.
# Copyright (c) 2017, Pierre Vignet
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.


import sys
import os
from setuptools import Extension, setup
import sysconfig
import toml
import pathlib
from sys import platform

def _parse_toml(pyproject_path):
    pyproject_text = pyproject_path.read_text()
    pyproject_data = toml.loads(pyproject_text)
    return pyproject_data['project']['version']


picosatlib = ('picosatlib', {
    'sources': [
               "python/cryptominisat/src/mpicosat/mpicosat.c",
               "python/cryptominisat/src/mpicosat/version.c"],
    'language' : "c",
    'include_dirs' : ["python/cryptominisat/src/"]
    })


def gen_modules(version):
    if platform == "win32" or platform == "cygwin":
        extra_compile_args_val = ['/std:c++17', "/DCMS_LOCAL_BUILD=1", "/DAPPMC_FULL_VERSION=\""+version+"\""]
        define_macros_val = [("TRACE", "")]

    else:
        extra_compile_args_val = ['-std=c++17']
        define_macros_val = [('CMS_LOCAL_BUILD', 1),("TRACE", ""),("APPMC_FULL_VERSION", "\""+version+"\"")]

    modules = Extension(
        name = "pyapproxmc",
        sources = [
                   "python/src/GitSHA1.cpp",
                   "python/src/pyapproxmc.cpp",
                   "src/approxmc.cpp",
                   "src/appmc_constants.cpp",
                   "src/counter.cpp",
                   "python/cryptominisat/python/src/GitSHA1.cpp",
                   "python/cryptominisat/src/backbone.cpp",
                   "python/cryptominisat/src/cardfinder.cpp",
                   "python/cryptominisat/src/ccnr_cms.cpp",
                   "python/cryptominisat/src/ccnr.cpp",
                   "python/cryptominisat/src/clauseallocator.cpp",
                   "python/cryptominisat/src/clausecleaner.cpp",
                   "python/cryptominisat/src/cnf.cpp",
                   "python/cryptominisat/src/completedetachreattacher.cpp",
                   "python/cryptominisat/src/cryptominisat.cpp",
                   "python/cryptominisat/src/datasync.cpp",
                   "python/cryptominisat/src/distillerbin.cpp",
                   "python/cryptominisat/src/distillerlitrem.cpp",
                   "python/cryptominisat/src/distillerlong.cpp",
                   "python/cryptominisat/src/distillerlongwithimpl.cpp",
                   "python/cryptominisat/src/frat.cpp",
                   "python/cryptominisat/src/gatefinder.cpp",
                   "python/cryptominisat/src/gaussian.cpp",
                   "python/cryptominisat/src/get_clause_query.cpp",
                   "python/cryptominisat/src/hyperengine.cpp",
                   "python/cryptominisat/src/intree.cpp",
                   "python/cryptominisat/src/lucky.cpp",
                   "python/cryptominisat/src/matrixfinder.cpp",
                   "python/cryptominisat/src/occsimplifier.cpp",
                   "python/cryptominisat/src/packedrow.cpp",
                   "python/cryptominisat/src/probe.cpp",
                   "python/cryptominisat/src/propengine.cpp",
                   "python/cryptominisat/src/reducedb.cpp",
                   "python/cryptominisat/src/sccfinder.cpp",
                   "python/cryptominisat/src/searcher.cpp",
                   "python/cryptominisat/src/searchstats.cpp",
                   "python/cryptominisat/src/sls.cpp",
                   "python/cryptominisat/src/solutionextender.cpp",
                   "python/cryptominisat/src/solverconf.cpp",
                   "python/cryptominisat/src/solver.cpp",
                   "python/cryptominisat/src/str_impl_w_impl.cpp",
                   "python/cryptominisat/src/subsumeimplicit.cpp",
                   "python/cryptominisat/src/subsumestrengthen.cpp",
                   "python/cryptominisat/src/vardistgen.cpp",
                   "python/cryptominisat/src/varreplacer.cpp",
                   "python/cryptominisat/src/xorfinder.cpp",
                   "python/cryptominisat/src/oracle/oracle.cpp",
                   "python/sbva/src/sbva.cpp",
                   "python/sbva/python/GitSHA1.cpp",
                   "python/arjun/src/arjun.cpp",
                   "python/arjun/src/backward.cpp",
                   "python/arjun/src/common.cpp",
                   "python/arjun/src/extend.cpp",
                   "python/arjun/src/puura.cpp",
                   "python/arjun/src/simplify.cpp",
                   "python/arjun/python/src/GitSHA1.cpp",
               ],
        depends = [
                   "python/sbva/src/getdelim.h",
                   "python/sbva/src/getline.h",
                   "python/sbva/src/murmur.h",
                   "python/sbva/src/sbva.h",
                   "python/sbva/src/time_mem.h",
                   "python/sbva/eigen-3.4.0/StdDeque",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseLU/SparseLU_pruneL.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseLU/SparseLU_Memory.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseLU/SparseLU_gemm_kernel.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseLU/SparseLU_Structs.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseLU/SparseLU_column_bmod.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseLU/SparseLU.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseLU/SparseLU_relax_snode.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseLU/SparseLU_column_dfs.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseLU/SparseLU_Utils.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseLU/SparseLU_pivotL.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseLU/SparseLU_copy_to_ucol.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseLU/SparseLU_heap_relax_snode.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseLU/SparseLU_panel_dfs.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseLU/SparseLU_kernel_bmod.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseLU/SparseLU_panel_bmod.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseLU/SparseLUImpl.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseLU/SparseLU_SupernodalMatrix.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseCore/SparseDiagonalProduct.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseCore/SparseBlock.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseCore/SparseView.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseCore/SparseSparseProductWithPruning.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseCore/SparseMap.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseCore/SparseCwiseUnaryOp.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseCore/SparseDenseProduct.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseCore/SparseMatrix.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseCore/SparseProduct.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseCore/SparseCwiseBinaryOp.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseCore/ConservativeSparseSparseProduct.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseCore/SparseTranspose.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseCore/SparseUtil.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseCore/SparseVector.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseCore/AmbiVector.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseCore/MappedSparseMatrix.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseCore/SparseFuzzy.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseCore/SparseTriangularView.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseCore/CompressedStorage.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseCore/SparseDot.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseCore/TriangularSolver.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseCore/SparsePermutation.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseCore/SparseColEtree.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseCore/SparseRedux.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseCore/SparseRef.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseCore/SparseAssign.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseCore/SparseMatrixBase.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseCore/SparseCompressedBase.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseCore/SparseSelfAdjointView.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseCore/SparseSolverBase.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/KLUSupport/KLUSupport.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/StlSupport/StdDeque.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/StlSupport/StdVector.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/StlSupport/details.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/StlSupport/StdList.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/LU/InverseImpl.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/LU/arch/InverseSize4.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/LU/PartialPivLU.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/LU/Determinant.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/LU/PartialPivLU_LAPACKE.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/LU/FullPivLU.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/PaStiXSupport/PaStiXSupport.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Jacobi/Jacobi.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/OrderingMethods/Eigen_Colamd.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/OrderingMethods/Amd.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/OrderingMethods/Ordering.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/MetisSupport/MetisSupport.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/UmfPackSupport/UmfPackSupport.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/misc/lapack.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/misc/Kernel.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/misc/lapacke.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/misc/Image.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/misc/lapacke_mangling.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/misc/RealSvd2x2.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/misc/blas.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Cholesky/LLT_LAPACKE.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Cholesky/LLT.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Cholesky/LDLT.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/Ref.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/ConditionEstimator.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/Transpositions.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/ArrayWrapper.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/StlIterators.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/Array.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/Visitor.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/Solve.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/MSA/PacketMath.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/MSA/MathFunctions.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/MSA/Complex.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/GPU/PacketMath.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/GPU/MathFunctions.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/GPU/TypeCasting.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/AltiVec/MatrixProduct.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/AltiVec/PacketMath.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/AltiVec/MatrixProductCommon.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/AltiVec/MathFunctions.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/AltiVec/MatrixProductMMA.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/AltiVec/Complex.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/NEON/PacketMath.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/NEON/GeneralBlockPanelKernel.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/NEON/MathFunctions.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/NEON/TypeCasting.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/NEON/Complex.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/AVX/PacketMath.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/AVX/MathFunctions.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/AVX/TypeCasting.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/AVX/Complex.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/Default/Half.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/Default/Settings.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/Default/ConjHelper.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/Default/GenericPacketMathFunctionsFwd.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/Default/BFloat16.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/Default/TypeCasting.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/Default/GenericPacketMathFunctions.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/SSE/PacketMath.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/SSE/MathFunctions.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/SSE/TypeCasting.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/SSE/Complex.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/ZVector/PacketMath.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/ZVector/MathFunctions.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/ZVector/Complex.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/HIP/hcc/math_constants.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/CUDA/Complex.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/AVX512/PacketMath.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/AVX512/MathFunctions.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/AVX512/TypeCasting.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/AVX512/Complex.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/SVE/PacketMath.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/SVE/MathFunctions.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/SVE/TypeCasting.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/SYCL/SyclMemoryModel.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/SYCL/PacketMath.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/SYCL/InteropHeaders.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/SYCL/MathFunctions.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/arch/SYCL/TypeCasting.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/NestByValue.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/ArrayBase.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/products/SelfadjointMatrixVector_BLAS.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/products/SelfadjointMatrixMatrix.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/products/TriangularSolverMatrix.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/products/GeneralMatrixMatrixTriangular_BLAS.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/products/GeneralMatrixMatrix_BLAS.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/products/GeneralBlockPanelKernel.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/products/GeneralMatrixVector.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/products/GeneralMatrixVector_BLAS.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/products/GeneralMatrixMatrix.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/products/TriangularMatrixMatrix_BLAS.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/products/TriangularMatrixVector_BLAS.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/products/TriangularSolverVector.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/products/SelfadjointMatrixVector.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/products/TriangularSolverMatrix_BLAS.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/products/SelfadjointProduct.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/products/SelfadjointRank2Update.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/products/TriangularMatrixVector.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/products/TriangularMatrixMatrix.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/products/Parallelizer.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/products/SelfadjointMatrixMatrix_BLAS.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/AssignEvaluator.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/Matrix.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/SelfAdjointView.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/MapBase.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/Transpose.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/DenseBase.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/CoreEvaluators.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/ProductEvaluators.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/Fuzzy.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/CwiseUnaryOp.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/util/ConfigureVectorization.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/util/IndexedViewHelper.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/util/StaticAssert.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/util/ReenableStupidWarnings.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/util/Macros.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/util/Constants.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/util/ReshapedHelper.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/util/DisableStupidWarnings.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/util/ForwardDeclarations.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/util/IntegralConstant.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/util/NonMPL2.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/util/Memory.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/util/SymbolicIndex.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/util/Meta.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/util/XprHelper.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/util/BlasUtil.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/util/MKL_support.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/Assign.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/MathFunctionsImpl.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/Inverse.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/Assign_MKL.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/SolverBase.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/DenseCoeffsBase.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/VectorBlock.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/SolveTriangular.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/NumTraits.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/SelfCwiseBinaryOp.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/VectorwiseOp.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/DenseStorage.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/Select.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/CommaInitializer.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/EigenBase.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/NoAlias.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/MathFunctions.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/Stride.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/ArithmeticSequence.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/IndexedView.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/CwiseTernaryOp.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/GenericPacketMath.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/DiagonalMatrix.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/GeneralProduct.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/CwiseNullaryOp.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/Swap.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/MatrixBase.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/Replicate.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/TriangularMatrix.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/StableNorm.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/Diagonal.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/PermutationMatrix.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/ForceAlignedAccess.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/Redux.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/BandMatrix.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/PartialReduxEvaluator.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/PlainObjectBase.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/CwiseUnaryView.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/Block.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/Reverse.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/Dot.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/Product.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/CoreIterators.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/DiagonalProduct.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/Random.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/CwiseBinaryOp.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/GlobalFunctions.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/Reshaped.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/ReturnByValue.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/IO.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/Map.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/BooleanRedux.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/functors/TernaryFunctors.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/functors/StlFunctors.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/functors/BinaryFunctors.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/functors/UnaryFunctors.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/functors/AssignmentFunctors.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Core/functors/NullaryFunctors.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SPQRSupport/SuiteSparseQRSupport.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/PardisoSupport/PardisoSupport.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseCholesky/SimplicialCholesky.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseCholesky/SimplicialCholesky_impl.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/plugins/CommonCwiseUnaryOps.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/plugins/CommonCwiseBinaryOps.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/plugins/MatrixCwiseBinaryOps.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/plugins/IndexedViewMethods.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/plugins/MatrixCwiseUnaryOps.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/plugins/ReshapedMethods.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/plugins/ArrayCwiseUnaryOps.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/plugins/BlockMethods.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/plugins/ArrayCwiseBinaryOps.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SuperLUSupport/SuperLUSupport.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Eigenvalues/RealSchur.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Eigenvalues/GeneralizedEigenSolver.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Eigenvalues/SelfAdjointEigenSolver_LAPACKE.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Eigenvalues/MatrixBaseEigenvalues.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Eigenvalues/ComplexSchur_LAPACKE.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Eigenvalues/ComplexSchur.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Eigenvalues/RealSchur_LAPACKE.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Eigenvalues/RealQZ.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Eigenvalues/EigenSolver.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Eigenvalues/Tridiagonalization.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Eigenvalues/ComplexEigenSolver.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Eigenvalues/HessenbergDecomposition.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/CholmodSupport/CholmodSupport.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SVD/BDCSVD.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SVD/UpperBidiagonalization.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SVD/SVDBase.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SVD/JacobiSVD_LAPACKE.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SVD/JacobiSVD.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/IterativeLinearSolvers/ConjugateGradient.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/IterativeLinearSolvers/IncompleteLUT.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/IterativeLinearSolvers/BiCGSTAB.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/IterativeLinearSolvers/IncompleteCholesky.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/IterativeLinearSolvers/LeastSquareConjugateGradient.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/IterativeLinearSolvers/SolveWithGuess.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/IterativeLinearSolvers/IterativeSolverBase.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/IterativeLinearSolvers/BasicPreconditioners.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Geometry/Rotation2D.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Geometry/arch/Geometry_SIMD.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Geometry/AlignedBox.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Geometry/Homogeneous.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Geometry/ParametrizedLine.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Geometry/Umeyama.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Geometry/RotationBase.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Geometry/Transform.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Geometry/EulerAngles.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Geometry/Hyperplane.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Geometry/Translation.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Geometry/Scaling.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Geometry/Quaternion.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Geometry/AngleAxis.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Geometry/OrthoMethods.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Householder/HouseholderSequence.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Householder/Householder.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/Householder/BlockHouseholder.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/QR/HouseholderQR_LAPACKE.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/QR/CompleteOrthogonalDecomposition.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/QR/HouseholderQR.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/QR/FullPivHouseholderQR.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/QR/ColPivHouseholderQR_LAPACKE.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/QR/ColPivHouseholderQR.h",
                   "python/sbva/eigen-3.4.0/Eigen/src/SparseQR/SparseQR.h",
                   "python/sbva/eigen-3.4.0/SparseLU",
                   "python/sbva/eigen-3.4.0/SparseCore",
                   "python/sbva/eigen-3.4.0/KLUSupport",
                   "python/sbva/eigen-3.4.0/LU",
                   "python/sbva/eigen-3.4.0/PaStiXSupport",
                   "python/sbva/eigen-3.4.0/Jacobi",
                   "python/sbva/eigen-3.4.0/OrderingMethods",
                   "python/sbva/eigen-3.4.0/MetisSupport",
                   "python/sbva/eigen-3.4.0/UmfPackSupport",
                   "python/sbva/eigen-3.4.0/Sparse",
                   "python/sbva/eigen-3.4.0/Cholesky",
                   "python/sbva/eigen-3.4.0/StdList",
                   "python/sbva/eigen-3.4.0/Core",
                   "python/sbva/eigen-3.4.0/SPQRSupport",
                   "python/sbva/eigen-3.4.0/PardisoSupport",
                   "python/sbva/eigen-3.4.0/SparseCholesky",
                   "python/sbva/eigen-3.4.0/Dense",
                   "python/sbva/eigen-3.4.0/SuperLUSupport",
                   "python/sbva/eigen-3.4.0/Eigenvalues",
                   "python/sbva/eigen-3.4.0/CholmodSupport",
                   "python/sbva/eigen-3.4.0/SVD",
                   "python/sbva/eigen-3.4.0/StdVector",
                   "python/sbva/eigen-3.4.0/Eigen",
                   "python/sbva/eigen-3.4.0/IterativeLinearSolvers",
                   "python/sbva/eigen-3.4.0/QtAlignedMalloc",
                   "python/sbva/eigen-3.4.0/Geometry",
                   "python/sbva/eigen-3.4.0/Householder",
                   "python/sbva/eigen-3.4.0/QR",
                   "python/sbva/eigen-3.4.0/SparseQR",
                   "python/sbva/src/GitSHA1.hpp",
                   "python/arjun/src/arjun.h",
                   "python/cryptominisat5/cryptominisat5.h",
        ],
        extra_compile_args = extra_compile_args_val,
        define_macros = define_macros_val,
        include_dirs = ["src/", "python/cryptominisat/src/", "python/arjun/src/", "python/sbva/src/", "python/arjun/", "python/sbva/eigen-3.4.0/", "python/sbva/eigen-3.4.0/Eigen/"],
        language = "c++",
    )
    return modules

if __name__ == '__main__':
    pyproject_path = pathlib.Path('pyproject.toml')
    version = _parse_toml(pyproject_path)
    modules = gen_modules(version)
    setup(
        ext_modules =  [modules],
        libraries = [picosatlib],
    )
